Repository googleinterns/step203-2020, pull requests merged in 2020-07, with the labels that each got.

#27 Add a test constants class
  src/test/java/com/google/step/TestConstants.java
Labels: suyash

#11 Add user model
  src/main/java/com/google/step/datamanager/UserManager.java
  src/main/java/com/google/step/datamanager/UserManagerDatastore.java
  src/main/java/com/google/step/model/User.java
  src/main/java/com/google/step/servlets/AuthenticationServlet.java
  src/main/webapp/WEB-INF/components/header.html
  src/main/webapp/WEB-INF/jsp/home.jsp
  src/main/webapp/WEB-INF/jsp/user.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/user.js
  src/main/webapp/js/util.js
Labels: anurag

#12 add blobstore for image upload
  src/main/java/com/google/step/servlets/ImageUploader.java
  src/main/java/com/google/step/servlets/ServeImageServlet.java
Labels: anurag

#20 Implement Search API using Index to search deals
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/datamanager/DealSearchManager.java
  src/main/java/com/google/step/datamanager/DealSearchManagerIndex.java
  src/main/java/com/google/step/servlets/DealSearchServlet.java
Labels: anurag

#15 Add user servlet
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/user-page.js
  src/main/webapp/js/util.js
Labels: anurag

#22 Add FollowManager and endpoint to manage followers (FollowServlet)
  pom.xml
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/servlets/FollowServlet.java
  src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/FollowServletTest.java
Labels: anurag

#21 Add VoteManager and endpoint to manage voting (VoteServlet)
  src/main/java/com/google/step/datamanager/VoteManager.java
  src/main/java/com/google/step/datamanager/VoteManagerDatastore.java
  src/main/java/com/google/step/servlets/VoteServlet.java
  src/test/java/com/google/step/datamanager/VoteManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/VoteServletTest.java
Labels: suyash

#23 Add UserServlet#doPost and tests
  src/main/java/com/google/step/datamanager/UserManager.java
  src/main/java/com/google/step/datamanager/UserManagerDatastore.java
  src/main/java/com/google/step/model/User.java
  src/main/java/com/google/step/servlets/AuthenticationServlet.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/user-page.js
  src/test/java/com/google/step/datamanager/UserManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: suyash

#18 Add validation for deal POST, endpoint for updating deal, and tests for deal POST servlet
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/main/java/com/google/step/servlets/DealPostServlet.java
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
  src/main/webapp/js/add-deal.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: suyash

#24 Add TagManager interface & TagManagerDatastore implementation
  src/main/java/com/google/step/datamanager/TagManager.java
  src/main/java/com/google/step/datamanager/TagManagerDatastore.java
  src/main/java/com/google/step/model/Tag.java
  src/test/java/com/google/step/datamanager/TagManagerDatastoreTest.java
Labels: suyash

#41 Add power mockito library for testing static class
  pom.xml
Labels: pod review

#28 Add deal tag manager and relevant tests
  src/main/java/com/google/step/datamanager/DealTagManager.java
  src/main/java/com/google/step/datamanager/DealTagManagerDatastore.java
  src/test/java/com/google/step/datamanager/DealTagManagerDatastoreTest.java
Labels: suyash

#33 Add endpoints for CommentServlet and tests
  src/main/java/com/google/step/servlets/CommentGetPostServlet.java
  src/main/java/com/google/step/servlets/CommentServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: anurag

#45 Update DealTagManagerDatastore.java
  src/main/java/com/google/step/datamanager/DealTagManagerDatastore.java
Labels: suyash, x-small

#9 Add frontend (JSP, CSS & JS) files for homepage
  src/main/webapp/WEB-INF/components/section-carousel.html
  src/main/webapp/WEB-INF/jsp/home.jsp
  src/main/webapp/css/styles.css
  src/main/webapp/js/home-page.js
Labels: suyash

#32 Create a new branch for CommentManager and CommentManagerDatastore and relevant tests
  pom.xml
  src/main/java/com/google/step/datamanager/CommentManager.java
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/java/com/google/step/model/Comment.java
  src/main/java/com/google/step/servlets/CommentGetPostServlet.java
  src/main/java/com/google/step/servlets/CommentServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: anurag

#37 Implement a search page (frontend) that calls the search api (backend) to search for deals based on description
  src/main/java/com/google/step/servlets/DealSearchServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/WEB-INF/jsp/search.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/search.js
  src/main/webapp/js/util.js
Labels: anurag

#39 Require authentication when user post deals
  src/main/java/com/google/step/servlets/DealPostServlet.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: suyash

#34 Add endpoints for RestaurantServlet as well as servlet tests
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantPostServlet.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/test/java/com/google/step/servlets/RestaurantPostServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: anurag

#31 Implement RestaurantManagerDatastore methods and tests
  pom.xml
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantPostServlet.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/RestaurantPostServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: suyash

#43 Change deal frontend to call the deal backend api
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/css/deals.css
  src/main/webapp/js/go-to-deal.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/JsonFormatterTest.java
Labels: suyash

#38 Add profile photo upload and tests
  src/main/java/com/google/step/datamanager/UserManagerDatastore.java
  src/main/java/com/google/step/servlets/ImageUploader.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/UserPostUrlServlet.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/js/user-page.js
  src/main/webapp/js/util.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/TagManagerDatastoreTest.java
  src/test/java/com/google/step/datamanager/UserManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/JsonFormatterTest.java
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: anurag

#50 Fix tests for comment servlet
  src/main/java/com/google/step/servlets/CommentGetPostServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: high priority, suyash

#49 Configure profile page follow button
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/servlets/FollowServlet.java
  src/main/webapp/js/user-page.js
Labels: anurag

#56 Implement backend for Restaurant Search by prefix name
  pom.xml
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/model/Restaurant.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantSearchServlet.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
Labels: anurag

#54 Modify header and footer
  src/main/webapp/WEB-INF/components/footer.html
  src/main/webapp/WEB-INF/components/header.html
  src/main/webapp/js/util.js
Labels: anurag

#63 Rename mockito's Matchers to ArgumentMatchers
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: suyash, x-small

#47 Update Vote backend: add user authentication to vote servlet, and add a doGet method to get what the user voted for
  src/main/java/com/google/step/datamanager/VoteManager.java
  src/main/java/com/google/step/datamanager/VoteManagerDatastore.java
  src/main/java/com/google/step/servlets/VoteServlet.java
  src/test/java/com/google/step/servlets/VoteServletTest.java
Labels: suyash

#64 Fix header login link
  src/main/webapp/js/util.js
Labels: pod review, suyash, x-small

#48 Add interface methods: read user/deal/tag list in data manager
  pom.xml
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/datamanager/TagManager.java
  src/main/java/com/google/step/datamanager/TagManagerDatastore.java
  src/main/java/com/google/step/datamanager/UserManager.java
  src/main/java/com/google/step/datamanager/UserManagerDatastore.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/test/java/com/google/step/datamanager/TagManagerDatastoreTest.java
  src/test/java/com/google/step/datamanager/UserManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: suyash

#44 Add tests for DealManagerDatastore
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/model/Deal.java
  src/main/java/com/google/step/model/Util.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
Labels: suyash

#51 Make the vote buttons on the deal page call the vote backend
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
Labels: anurag

#46 Add a list of tagNames as arguments to createDeal and updateDeal
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/main/java/com/google/step/servlets/DealPostServlet.java
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: suyash

#53 Add timestamp property to deals
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/model/Deal.java
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/datamanager/DealSearchManagerIndexTest.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: anurag

#55 Add updating tags followed by users
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/js/user-page.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: suyash

#73 Remove duplicate imgage url constants in TestConstants
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/JsonFormatterTest.java
Labels: suyash, x-small

#57 Update user servlet to call other data managers and update tests
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: anurag

#60 Add a default profile photo option in user profile
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/images/default-profile-pic.svg
  src/main/webapp/js/user-page.js
Labels: anurag

#78 Fix when the cancel button is pressed while editing user profile
  src/main/webapp/js/user-page.js
Labels: suyash, x-small

#52 Add methods for dealManager interface and create transformEntitytoDeal method
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/model/Deal.java
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
  src/test/java/com/google/step/datamanager/DealSearchManagerIndexTest.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: anurag

#62 Implement a POST Restaurant page (frontend) with maps api to search for places
  src/main/webapp/WEB-INF/jsp/add-restaurant.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/add-deal.js
  src/main/webapp/js/add-restaurant.js
  src/main/webapp/js/util.js
Labels: suyash

#75 Add authentication to FollowServlet for doPost and doDelete methods
  src/main/java/com/google/step/servlets/FollowServlet.java
  src/test/java/com/google/step/servlets/FollowServletTest.java
Labels: suyash

#80 add function to search bar on home page
  src/main/webapp/WEB-INF/jsp/home.jsp
Labels: suyash, x-small

#69 Link POST restaurant to backend
  src/main/java/com/google/step/servlets/RestaurantPostServlet.java
  src/main/java/com/google/step/servlets/RestaurantPostUrlServlet.java
  src/main/webapp/js/add-restaurant.js
  src/test/java/com/google/step/servlets/RestaurantPostServletTest.java
Labels: suyash

#66 Add restaurant page with hard-coded info
  src/main/webapp/WEB-INF/jsp/restaurant.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/restaurant-page.js
  src/main/webapp/js/user-page.js
Labels: suyash

#65 Update comment json to include user brief info, and link frontend's POST comment to backend
  src/main/java/com/google/step/datamanager/UserManagerDatastore.java
  src/main/java/com/google/step/servlets/CommentGetPostServlet.java
  src/main/java/com/google/step/servlets/CommentServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: anurag

#68 Make comment frontend display real comments from backend
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#85 Remove poster, restaurant and votes from brief deal json
  src/main/java/com/google/step/servlets/JsonFormatter.java
Labels: pod review, suyash, x-small

#70 Fix TODOs in DealPostServlet : verify that selected restaurant exists, and add tag parameter
  src/main/java/com/google/step/servlets/DealPostServlet.java
  src/test/java/com/google/step/servlets/DealPostServletTest.java
Labels: suyash

#87 Refractor CommentManagerDatastore tests to use TestConstants and override equals method in Comment for assertEquals
  src/main/java/com/google/step/model/Comment.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
Labels: high priority, suyash

#61 Implemented methods for retrieving deals based on followed Users/Restaurants/Tags
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
Labels: suyash

#88 Update vote manger tests: use TestConstants and swap assertEquals' expected/actual arguments
  src/test/java/com/google/step/datamanager/VoteManagerDatastoreTest.java
Labels: suyash

#71 Update DealDetailServlet to get real restaurants & tags, and add authentication to delete
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantSearchServlet.java
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: suyash

#91 show tags on deal page
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#97 Use test constants for DealTagManagerDatastoreTest
  src/test/java/com/google/step/datamanager/DealTagManagerDatastoreTest.java
Labels: anurag, pod review, x-small

#89 Update deal card (frontend) and make every page use the same deal card
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/css/deal.css
  src/main/webapp/css/styles.css
  src/main/webapp/js/user-page.js
  src/main/webapp/js/util.js
Labels: anurag

#74 Add isFollowing in follow manager and servlet and tests
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/servlets/FollowServlet.java
  src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/FollowServletTest.java
Labels: suyash

#98 Remove duplicate getRestaurantBriefMap method
  src/main/java/com/google/step/servlets/JsonFormatter.java
Labels: high priority, pod review, suyash, x-small

#82 Add a page which lists all the deals
  src/main/java/com/google/step/servlets/DealServlet.java
  src/main/webapp/WEB-INF/components/header.html
  src/main/webapp/WEB-INF/jsp/all-deals.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/all-deals.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/DealServletTest.java
Labels: suyash

#79 Add a script for populating restaurants database
  src/main/java/com/google/step/datamanager/RestaurantGenerator.java
  src/main/java/com/google/step/servlets/RestaurantGeneratorServlet.java
  src/main/resources/restaurants.txt
Labels: suyash

#67 Create HomePageServlet and test to fetch data for Home Page, modify frontend to display data fetched
  src/main/java/com/google/step/servlets/HomePageServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/WEB-INF/jsp/home.jsp
  src/main/webapp/js/home-page.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/HomePageServletTest.java
Labels: suyash

#81 Add photo urls of generated restaurants
  src/main/java/com/google/step/datamanager/RestaurantGenerator.java
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/model/Restaurant.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantPostServlet.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/RestaurantPostServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: anurag

#77 Add Authentication for HomePageServlet
  src/main/java/com/google/step/servlets/HomePageServlet.java
  src/test/java/com/google/step/servlets/HomePageServletTest.java
Labels: suyash

#102 Allow deleting comment from the frontend
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#84 Link restaurant page frontend to backend
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/main/webapp/js/restaurant-page.js
  src/main/webapp/js/user-page.js
Labels: anurag

#103 Remove duplicate Deal Brief Json
  src/test/java/com/google/step/TestConstants.java
Labels: high priority, suyash, x-small

#83 Front end for home page authentication
  src/main/webapp/js/home-page.js
Labels: suyash

#104 Allow editing comment from the frontend
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#110 Fix copyright symbol in footer
  src/main/webapp/WEB-INF/components/footer.html
Labels: suyash, x-small

#100 Add restaurant place manager
  src/main/java/com/google/step/datamanager/RestaurantPlaceManager.java
  src/main/java/com/google/step/datamanager/RestaurantPlaceManagerDatastore.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantPostServlet.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/RestaurantPlaceManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/RestaurantPostServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: suyash

#109 Add a index.yaml file
  src/main/webapp/WEB-INF/index.yaml
Labels: pod review, suyash, x-small

#107 Allow user to delete deal from frontend
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#114 Disallow logged out user to vote
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#96 Resized search bar and separated home page styles from styles.css
  src/main/webapp/WEB-INF/jsp/home.jsp
  src/main/webapp/css/home-page.css
  src/main/webapp/css/styles.css
Labels: suyash

#113 Hide server side api key
  .gitignore
  src/main/java/com/google/step/datamanager/RestaurantGenerator.java
  src/main/java/com/google/step/model/Restaurant.java
Labels: suyash

#111 Make user stay on the same page after logging in/out
  src/main/java/com/google/step/servlets/AuthenticationServlet.java
  src/main/webapp/js/util.js
Labels: suyash

#121 Fix follow button
  src/main/webapp/js/user-page.js
Labels: suyash, x-small

#122 Fix user brief json
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/test/java/com/google/step/TestConstants.java
Labels: suyash, x-small

#123 Add a fake api key in restaurant generator
  src/main/java/com/google/step/datamanager/RestaurantGenerator.java
Labels: pod review, suyash, x-small

#112 Implement a page which lists all restaurants (frontend + backend)
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/servlets/RestaurantPostListServlet.java
  src/main/webapp/WEB-INF/components/header.html
  src/main/webapp/WEB-INF/jsp/all-restaurants.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/css/all-restaurants.css
  src/main/webapp/js/all-restaurants.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/RestaurantPostListServletTest.java
Labels: suyash

#95 Add a form to edit deal (frontend)
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/css/add-deal.css
  src/main/webapp/css/styles.css
  src/main/webapp/js/add-deal.js
  src/main/webapp/js/form-validity-util.js
  src/main/webapp/js/go-to-deal.js
  src/main/webapp/js/restaurant-search-util.js
Labels: suyash

#118 Update json formatter tests
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/JsonFormatterTest.java
Labels: suyash

#93 Add a map showing restaurant branches to restaurant page
  src/main/webapp/WEB-INF/jsp/restaurant.jsp
  src/main/webapp/js/restaurant-page.js
Labels: anurag

#94 Add ability of user to view all deals for a particular section
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/servlets/HomePageServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/js/home-page.js
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/HomePageServletTest.java
Labels: anurag

#124 Hide submit deal form if user is logged out
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
  src/main/webapp/js/add-deal.js
Labels: suyash

#129 Change logout to delete cookie instead of using UserService
  src/main/java/com/google/step/servlets/AuthenticationServlet.java
  src/main/java/com/google/step/servlets/LogoutServlet.java
Labels: anurag, pod review

#131 Change restaurant search to food search
  src/main/webapp/js/add-restaurant.js
Labels: pod review, suyash, x-small

#127 Make deal card have object fit cover
  src/main/webapp/css/home-page.css
  src/main/webapp/css/styles.css
  src/main/webapp/js/home-page.js
Labels: suyash

#101 Update comments backend + frontend to paginate comments
  src/main/java/com/google/step/datamanager/CommentManager.java
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/java/com/google/step/datamanager/CommentsWithToken.java
  src/main/java/com/google/step/servlets/CommentGetPostServlet.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/CommentGetPostServletTest.java
Labels: anurag

#125 Check image extension from frontend when submitting deals
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
  src/main/webapp/js/add-deal.js
Labels: suyash

#133 Hide edit deal button if logged in user is not poster
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
Labels: suyash

#126 Update user servlet doGet test
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: suyash

#106 Add more verification to deal update and allow tags parameter (backend), and add tags to the update deal form (frontend)
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/main/webapp/WEB-INF/jsp/deals.jsp
  src/main/webapp/js/go-to-deal.js
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: suyash

#139 Escape html in restaurant search
  src/main/webapp/js/add-deal.js
  src/main/webapp/js/restaurant-search-util.js
  src/main/webapp/js/util.js
Labels: suyash

#140 When deal is deleted, also delete comments on the deal
  src/main/java/com/google/step/datamanager/CommentManager.java
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: suyash

#147 Fix compile error in comment manager test
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
Labels: high priority, pod review, suyash

#141 Make deleting deal also delete its blobkey
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: suyash

#120 Add a mail manager and send notification emails to followers of new deal poster
  pom.xml
  src/main/java/com/google/step/datamanager/MailManager.java
  src/main/java/com/google/step/servlets/DealServlet.java
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
  src/test/java/com/google/step/servlets/DealServletTest.java
Labels: suyash
