Repository googleinterns/step203-2020, pull requests merged in 2020-08, with the labels that each got.

#138 Add username validation
  src/main/java/com/google/step/servlets/UserServlet.java
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/js/user-page.js
  src/test/java/com/google/step/servlets/UserServletTest.java
Labels: suyash

#137 Add authentication to Deal Update (backend)
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: anurag

#156 Fix deal link in mail
  src/main/java/com/google/step/datamanager/MailManager.java
Labels: pod review, suyash, x-small

#108 Front end for viewing all deals for each section of home page
  src/main/webapp/WEB-INF/components/section-carousel.html
  src/main/webapp/WEB-INF/jsp/all-section-deals.jsp
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/js/all-section-deals.js
  src/main/webapp/js/home-page.js
  src/main/webapp/js/util.js
Labels: anurag

#152 Delete blobkeys when deleting restaurants
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/servlets/ImageUploader.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
Labels: suyash

#150 Add not found restaurant page
  src/main/webapp/WEB-INF/jsp/restaurant.jsp
  src/main/webapp/js/restaurant-page.js
Labels: suyash

#153 Add not found user page
  src/main/webapp/WEB-INF/jsp/user-page.jsp
  src/main/webapp/js/user-page.js
Labels: suyash

#149 Update post restaurant servlet to save placeIds
  src/main/java/com/google/step/servlets/RestaurantPostListServlet.java
  src/test/java/com/google/step/servlets/RestaurantPostListServletTest.java
Labels: suyash

#159 Fix logout for IAM authentication
  src/main/java/com/google/step/servlets/LogoutServlet.java
Labels: suyash

#119 Create a new DealVoteCountManager to handle DealVote datastore
  src/main/java/com/google/step/datamanager/DealVoteCountManager.java
  src/main/java/com/google/step/datamanager/DealVoteCountManagerDatastore.java
  src/main/java/com/google/step/servlets/VoteServlet.java
  src/main/java/com/google/step/servlets/VotingHelper.java
  src/test/java/com/google/step/datamanager/DealVoteCountManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/VoteServletTest.java
  src/test/java/com/google/step/servlets/VotingHelperTest.java
Labels: suyash

#143 Verify that only poster of comment can delete/update that comment (backend)
  src/main/java/com/google/step/datamanager/CommentManager.java
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/java/com/google/step/servlets/CommentServlet.java
  src/test/java/com/google/step/datamanager/CommentManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: suyash

#167 Change trending deals to sort by descending
  src/main/java/com/google/step/servlets/HomePageServlet.java
Labels: pod review, suyash, x-small

#161 Allow updating restaurant places in backend
  src/main/java/com/google/step/servlets/RestaurantServlet.java
Labels: suyash

#154 Delete places and followers of restaurant in restaurant servlet doDelete
  src/main/java/com/google/step/datamanager/FollowManager.java
  src/main/java/com/google/step/datamanager/FollowManagerDatastore.java
  src/main/java/com/google/step/datamanager/RestaurantPlaceManager.java
  src/main/java/com/google/step/datamanager/RestaurantPlaceManagerDatastore.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/test/java/com/google/step/datamanager/FollowManagerDatastoreTest.java
  src/test/java/com/google/step/datamanager/RestaurantPlaceManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: suyash

#166 Use tag container for home page deals
  src/main/webapp/js/go-to-deal.js
  src/main/webapp/js/util.js
Labels: pod review, suyash, x-small

#142 Add comment sentiment attribute to comment
  pom.xml
  src/main/java/com/google/step/datamanager/CommentManagerDatastore.java
  src/main/java/com/google/step/model/Comment.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/CommentServletTest.java
Labels: anurag

#168 Add a favicon
  src/main/webapp/favicon.ico
Labels: pod review, suyash, x-small

#145 When deal is deleted, also delete tags relationship on the deal
  src/main/java/com/google/step/datamanager/DealTagManager.java
  src/main/java/com/google/step/datamanager/DealTagManagerDatastore.java
  src/main/java/com/google/step/servlets/DealDetailServlet.java
  src/test/java/com/google/step/datamanager/DealTagManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/DealDetailServletTest.java
Labels: suyash

#144 Add poster to restaurant object and deleting restaurant frontend
  src/main/java/com/google/step/datamanager/RestaurantGenerator.java
  src/main/java/com/google/step/datamanager/RestaurantManager.java
  src/main/java/com/google/step/datamanager/RestaurantManagerDatastore.java
  src/main/java/com/google/step/model/Restaurant.java
  src/main/java/com/google/step/servlets/JsonFormatter.java
  src/main/java/com/google/step/servlets/RestaurantPostListServlet.java
  src/main/java/com/google/step/servlets/RestaurantServlet.java
  src/main/webapp/WEB-INF/jsp/restaurant.jsp
  src/main/webapp/js/restaurant-page.js
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/datamanager/RestaurantManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/RestaurantPostListServletTest.java
  src/test/java/com/google/step/servlets/RestaurantServletTest.java
Labels: suyash

#169 Add loading symbol for home page
  src/main/webapp/WEB-INF/components/section-carousel.html
  src/main/webapp/js/home-page.js
Labels: pod review, suyash, x-small

#170 Add loading symbol for section
  src/main/webapp/WEB-INF/jsp/all-section-deals.jsp
  src/main/webapp/js/all-section-deals.js
Labels: pod review, suyash, x-small

#171 Fix bug with viewing all deals link
  src/main/webapp/js/home-page.js
Labels: high priority, suyash, x-small

#172 Remove deal style reference
  src/main/webapp/WEB-INF/jsp/add-deal.jsp
Labels: pod review, x-small

#162 Add sorting to deal manager get deals
  src/main/java/com/google/step/datamanager/DealManager.java
  src/main/java/com/google/step/datamanager/DealManagerDatastore.java
  src/main/java/com/google/step/servlets/HomePageServlet.java
  src/test/java/com/google/step/datamanager/DealManagerDatastoreTest.java
  src/test/java/com/google/step/servlets/HomePageServletTest.java
Labels: anurag

#163 Add limit to deal vote count manager
  src/main/java/com/google/step/datamanager/DealVoteCountManager.java
  src/main/java/com/google/step/datamanager/DealVoteCountManagerDatastore.java
  src/test/java/com/google/step/datamanager/DealVoteCountManagerDatastoreTest.java
Labels: anurag

#164 Integrate sorting in home page servlet
  src/main/java/com/google/step/servlets/HomePageServlet.java
  src/main/webapp/WEB-INF/index.yaml
  src/test/java/com/google/step/TestConstants.java
  src/test/java/com/google/step/servlets/HomePageServletTest.java
Labels: anurag

#135 Front end for sorting deals from each section
  src/main/webapp/WEB-INF/jsp/all-section-deals.jsp
  src/main/webapp/js/all-section-deals.js
Labels: anurag
